[tool.poetry]
name = "timeback"
version = "0.1.1"
description = "A Python client for the TimeBack API (OneRoster 1.2 implementation)"
authors = ["Casey Schmid <casey.schmid@2hourlearning.com>"]
readme = "README.md"
packages = [{ include = "timeback" }]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.12.3"
httpx = "^0.27.2"
python-dotenv = "^1.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "integration: marks tests as integration tests (require real API access)",
]
